### ISSUE TITLE
There is a Stored XSS with EasyCMS

### ISSUE THREAD

**Issue by starnightcyber** [teameasy/EasyCMS#2]
## Stored XSS found when post an article 

Steps To Reproduce:
1、Login the backstage:
http://localhost/EasyCMS-master//index.php?s=/admin/login/login.html
2、Before post an article, you need to create an article classification, now we have class - "a"
![image](https://user-images.githubusercontent.com/19260696/39316917-f2082762-49ac-11e8-8480-f0d2e399b5a3.png)
3、Then post a new article or edit an existing one
![image](https://user-images.githubusercontent.com/19260696/39317093-587e03d6-49ad-11e8-8652-c47b537b98fa.png)
4、No 1.2.3.4 is a simple test to check whether field is vulnerable to stored xss
a)tilte filed
![image](https://user-images.githubusercontent.com/19260696/39317579-8588301c-49ae-11e8-83ce-70f943f4f81b.png)
b)keyword field
![image](https://user-images.githubusercontent.com/19260696/39317590-8d681f72-49ae-11e8-9fad-d2fb22108465.png)
Then go to the site front page : http://localhost/EasyCMS-master/
c)abstract field 
![image](https://user-images.githubusercontent.com/19260696/39317605-99414af8-49ae-11e8-980b-8511335e5264.png)
Then click the article to see more
d)content filed
![image](https://user-images.githubusercontent.com/19260696/39317620-a7291312-49ae-11e8-9288-850cc63c2184.png)
The Above four fields are prone to store xss attack

**Comment by chenrui1896** [comment]
后台出xss危害大吗

**Comment by chenjiesuper** [comment]
no protection in the management background，we are not going to deal with it

**Comment by sqlsec** [comment]
@chenrui1896 CVE收这种漏洞 存在即合理

**Comment by chenrui1896** [comment]
@sqlsec 了解
